Expo eject to a bare workflow (#40)
* expo eject
Able to get it working by following
https://medium.com/@adityasingh_32512/solved-unable-to-load-script-from-assets-index-android-bundle-bdc5e3a3d5ff

* expo eject ios

* make  ./gradlew bundleRelease work
* Faced duplicate resources issue while building the apk
* has to remove resource files from src directory because build also has
generated files.
Example error:
[raw/node_modules_expo_vectoricons_build_vendor_reactnativevectoricons_fonts_materialicons]
/src/main/res/raw/node_modules_expo_vectoricons_build_vendor_reactnativevectoricons_fonts_materialicons.ttf
[raw/node_modules_expo_vectoricons_build_vendor_reactnativevectoricons_fonts_materialicons]
build/generated/res/react/release/raw/node_modules_expo_vectoricons_build_vendor_reactnativevectoricons_fonts_materialicons.ttf:
Error: Duplicate resources

* change from com.croma to app.croma

* cleanup and readme update

* update launcher icon
* TODO: need to fix this. Temp working icon for now

* fix size of icons